server:
  port: 8080

spring:
  jackson:
    time-zone: Europe/Moscow
  datasource:
    name: nadojob_db
    password: ivanmilovanov
    url: jdbc:postgresql://localhost:5432/nadojob_db
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    properties:
      hibernate.format_sql: true
      hibernate.type:
        descriptor:
          sql: trace
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect           # добавить
      hibernate.type.preferred_enum_jdbc_type: named_enum                   # добавить

security:
  jwt:
    secret_key: 7a5ee5fb1131d6f93e798b622047ab00ff3a2b1f38818cb8d4c37ce119eb391b
    access_token_expiration: 3600000         # 1 час = 3 600 000 мс
    refresh_token_expiration: 86400000       # 1 день = 86 400 000 мс